window.GeradorRotinasJsonPadrao = {
  state: {
    fields: [],
    globalIndexes: [],
    tabs: [],
    customButtons: [],
    gridColumns: [],
    parentGrid: null,
    activeGridLocation: "parent",
    activePreview: "parent",
    activeMacRoutine: "parent",
    activeRuleRoutine: "rg",
    ruleHooks: {},
    layoutSuggestions: {
      tabPanelLineAuto: true,
      tabPanelHeightAuto: true,
      btnManterLineAuto: true,
      windowHeightAuto: true
    }
  },

  fieldTypes: [
    ["integer", "Inteiro"],
    ["string", "String"],
    ["textArea", "Área de texto"],
    ["float", "Float"],
    ["decimal", "Decimal"],
    ["date", "Data"],
    ["monthYear", "Mês/Ano"],
    ["combo", "ComboBox"],
    ["checkbox", "CheckBox"],
    ["radio", "RadioButton"],
    ["multiSelect", "Multi-Seleção"]
  ],

  buttonIcons: [
    ["", "Sem ícone"],
    ["truck", "truck — Transportadora"],
    ["check", "check — Confirmar"],
    ["pencil", "pencil — Editar"],
    ["plus", "plus — Adicionar"],
    ["excluir", "excluir — Excluir"],
    ["attach", "attach — Clip 📎"],
    ["trash", "trash — Lixeira 🗑️"],
    ["lock", "lock — Cadeado fechado 🔒"],
    ["unlock", "unlock — Cadeado aberto 🔓"],
    ["send", "send — Aviãozinho 📨"],
    ["clock", "clock — Relógio ⏰"],
    ["mail", "mail — Envelope ✉️"],
    ["refresh", "refresh — Atualizar 🔄"],
    ["search", "search — Lupa 🔍"],
    ["inbox", "inbox — Download 📥"],
    ["box", "box — Caixa 📦"],
    ["folder", "folder — Pasta 📁"],
    ["add", "add — Adicionar ➕"],
    ["remove", "remove — Remover ➖"],
    ["settings", "settings — Configurações ⚙️"],
    ["mobile", "mobile — Celular 📱"],
    ["idea", "idea — Ideia 💡"],
    ["editar", "editar — Editar (padrão CSW) 📝"],
    ["edit", "edit — Editar 📝"],
    ["cart", "cart — Carrinho 🛒"],
    ["back", "back — Voltar 🔙"],
    ["forward", "forward — Avançar 🔜"],
    ["chat", "chat — Conversa 💬"],
    ["call", "call — Telefone 📞"],
    ["announcement", "announcement — Megafone 📢"],
    ["signal", "signal — Sinal 📶"],
    ["compass", "compass — Bússola 🧭"],
    ["home", "home — Casa 🏠"],
    ["map", "map — Mapa 🗺️"],
    ["stop", "stop — Parar ⏹️"],
    ["smile", "smile — Feliz 😊"]
  ]
};
